"""new migration

Revision ID: 3094274f2ebb
Revises: 
Create Date: 2023-04-10 17:21:39.635126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3094274f2ebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('repo_id', 'repo_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo')
    # ### end Alembic commands ###
